language: node.js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/
  target-branch: gh-pages
  commit: "Travis deploy"
  on:
    branch: master
